USE web_db;

-- CHAT_ROOM 테이블 생성
CREATE TABLE IF NOT EXISTS CHAT_ROOM (
    ROOM_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    SELLER_ID INT NOT NULL,
    BUYER_ID INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    FOREIGN KEY (SELLER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (BUYER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    UNIQUE KEY unique_room (PRODUCT_ID, SELLER_ID, BUYER_ID)
);

-- CHAT_MESSAGE 테이블 생성
CREATE TABLE IF NOT EXISTS CHAT_MESSAGE (
    MESSAGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROOM_ID INT NOT NULL,
    SENDER_ID INT NOT NULL,
    message TEXT NOT NULL,
    is_read TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ROOM_ID) REFERENCES CHAT_ROOM(ROOM_ID) ON DELETE CASCADE,
    FOREIGN KEY (SENDER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_chat_room_product_id ON CHAT_ROOM(PRODUCT_ID);
CREATE INDEX IF NOT EXISTS idx_chat_room_seller_id ON CHAT_ROOM(SELLER_ID);
CREATE INDEX IF NOT EXISTS idx_chat_room_buyer_id ON CHAT_ROOM(BUYER_ID);
CREATE INDEX IF NOT EXISTS idx_chat_message_room_id ON CHAT_MESSAGE(ROOM_ID);
CREATE INDEX IF NOT EXISTS idx_chat_message_sender_id ON CHAT_MESSAGE(SENDER_ID);
CREATE INDEX IF NOT EXISTS idx_chat_message_created_at ON CHAT_MESSAGE(created_at);

