USE web_db;

-- USER 테이블 (사용자)
CREATE TABLE IF NOT EXISTS USER (
    id VARCHAR(255) PRIMARY KEY,
    USER_ID INT AUTO_INCREMENT,
    email VARCHAR(255) UNIQUE NOT NULL,
    nickname VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    money INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active TINYINT(1) DEFAULT 1
);

-- PRODUCT 테이블 (상품)
CREATE TABLE IF NOT EXISTS PRODUCT (
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    SELLER_ID INT NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    description TEXT,
    image_url LONGBLOB,
    delivery_method VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_sold TINYINT(1) DEFAULT 0,
    FOREIGN KEY (SELLER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

-- QNA 테이블 (문의사항)
CREATE TABLE IF NOT EXISTS QNA (
    QNA_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    question TEXT NOT NULL,
    answer TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

-- TRANSACTION 테이블 (거래)
CREATE TABLE IF NOT EXISTS TRANSACTION (
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    BUYER_ID INT NOT NULL,
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    FOREIGN KEY (BUYER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

-- REVIEW 테이블 (리뷰)
CREATE TABLE IF NOT EXISTS REVIEW (
    REVIEW_ID INT AUTO_INCREMENT PRIMARY KEY,
    TRANSACTION_ID INT NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION(TRANSACTION_ID) ON DELETE CASCADE
);

-- 인덱스 생성
CREATE INDEX idx_product_seller_id ON PRODUCT(SELLER_ID);
CREATE INDEX idx_product_is_sold ON PRODUCT(is_sold);
CREATE INDEX idx_qna_user_id ON QNA(USER_ID);
CREATE INDEX idx_transaction_product_id ON TRANSACTION(PRODUCT_ID);
CREATE INDEX idx_transaction_buyer_id ON TRANSACTION(BUYER_ID);
CREATE INDEX idx_review_transaction_id ON REVIEW(TRANSACTION_ID);
